### ISSUE TITLE
Remember-me login, extra authorization

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-api#109]
If we introduce remember-me login, we increase the chance that someone who isn't supposed to access a page does so anyway. Spring allows for isFullyAuthenticated() in the PreAuthorize tags. If that is enabled, the user needs a "fresh" session. Might be good for ticket transfer sections...

**Comment by Icety** [comment]
Not relevant anymore, replaced by token based authentication.
