### ISSUE TITLE
Removing the first ticket removes 2 tickets

### ISSUE THREAD

**Issue by Icety** [AreaFiftyLAN/lancie-api#129]
When you click the delete button of the first ticket when having 2 or more tickets, both the first and second ticket get visually deleted. 
The first ticket is actually deleted and the second only on the fronted, refreshing the page will show it again.

I discovered that it goes wrong somewhere after the 'ticketReload' method.

**Comment by TimvdLippe** [comment]
Moved to https://github.com/AreaFiftyLAN/lancie-frontend/issues/53
