### ISSUE TITLE
Return other error message than 400

### ISSUE THREAD

**Issue by Icety** [AreaFiftyLAN/lancie-api#131]
When an ajax calls generates errors, for instance when a field is not correctly entered in a form, the api returns a 400 error. The browser however throws an error in the console when this happens, even when it actually returns valid information.

Since browsers just want a 200 message, we should send this back, even when errors occur. Polymer should what to do based on the data that is returned and then show an error.

**Comment by skamoen** [comment]
This needs to be more specific, as this is not general behaviour. Which calls return which 400 where you expect a 200 OK?

**Comment by Icety** [comment]
On the my-area page:

- http://localhost:5100/api/v1/users/current/orders/open - Failed to load resource: the server responded with a status of 404 (Not Found): No open orders were found
- POST http://localhost:5100/api/v1/users/current/profile 403 (Forbidden): Editing profile: Profilename needs to be set

**Comment by skamoen** [comment]
The open orders one should return 200, with just an empty array/object if no orders are found. 

The 2nd one is weird, I'd expect a bad request there.
