### ISSUE TITLE
Username reset

### ISSUE THREAD

**Issue by mpasterkamp** [AreaFiftyLAN/lancie-api#150]
Right now, it is impossible to retrieve your username if you happen to forget your username or if you created your account with a typo in the username. I would love to see a method to retrieve/change your username

**Comment by skamoen** [comment]
I guess we could add a "Request username" call. Your username is also stated in the confirmation mail though, it's the name right after "Dear"

**Comment by Icety** [comment]
Login will be done through email, so no longer relevant.
