### ISSUE TITLE
Deal with expired verification tokens

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-api#152]
Once the deadline for verification has passed, there's no way to verify an account anymore. There are two ways of solving this

1. Implement #97 to include unverified accounts with expired tokens
2. Allow for requesting another confirmation mail. 

I'm leaning towards 1.

**Comment by TimvdLippe** [comment]
Yes I would vote for 1 too. It seems more secure and more logical.

**Comment by martijn9612** [comment]
I am also preferring 1 over 2. I would mention that a timer of 30 minutes to activate the account is a bit on the short side, why not increase this token to 2 or 3 hours? Some mailservers are really slow and some people just forget.

**Comment by skamoen** [comment]
Who said anything about 30 minutes. It's 24 hours, after the token expires. It only checks for expired tokens every 30 minutes.

**Comment by martijn9612** [comment]
Then 1 should be the best way to go.
