### ISSUE TITLE
Usernames should be all case-insensitive

### ISSUE THREAD

**Issue by martijn9612** [AreaFiftyLAN/lancie-api#158]
This should happen when creating accounts, searching and logging in. Every time something is done with an username gotten trough an external source, the username should be lowercase.

**Comment by skamoen** [comment]
I wouldn't force usernames to be all lowercase, as these might be quite important for the readability of certain username. Make any operation involving usernames case-insensitive would be a better idea. 

Not sure how feasible this is to fix on the short-term though.

**Comment by bvanderdrift** [comment]
I'd just like to add that I think this is a good idea, but indeed we shouldn't force unames to be lowercased. Just make check case insensitive.

**Comment by skamoen** [comment]
Fixed in #214
