### ISSUE TITLE
Remove JavaDoc class template

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-api#187]
https://github.com/AreaFiftyLAN/lancie-api/search?utf8=%E2%9C%93&q=%2F**+Created+by+on&type=Code

You can permanently disable this at `File -> Settings -> Editor -> File and Code Templates -> Class` or else `File -> Settings -> Editor -> File and Code Templates -> Includes -> File Header`

**Comment by skamoen** [comment]
Why do we want that gone? I kinda like it

**Comment by TimvdLippe** [comment]
In my opinion it really clutters the code and provides no useful context other than stating which developer generated the file in his/her IDE.

**Comment by skamoen** [comment]
Fixed in #306
