### ISSUE TITLE
Make tickets redeemable

### ISSUE THREAD

**Issue by bvanderdrift** [AreaFiftyLAN/lancie-api#190]
Tickets are currently just "owned" and can be transferred. It's weird that someone can own multiple tickets. If a user has multiple tickets, weird relations exist between users.

For example, a captain who can choose seats for his members, need to chose one seat for every member. But seats are linked to tickets (logically). So what if someone 'owns' multiple tickets?

If a user buys multiple tickets he/she would get one automatically assigned and the others are in some 'inactive' state waiting to be transferred or 'gifted' to users, who then redeem the ticket.

**Comment by Icety** [comment]
Replaced by #264
