### ISSUE TITLE
Add endpoint to get all tickets and owners

### ISSUE THREAD

**Issue by martijn9612** [AreaFiftyLAN/lancie-api#223]
We currently do not have an endpoint to get all tickets and it's owner. This comes in handy for an admin to verify that the user is allowed at the event.

**Comment by skamoen** [comment]
Could you work this out in more detail what you want to do (both in front-end as back-end)? A general `/tickets` endpoint is easily created, but I'm not sure what it is exactly what you want to do.

**Comment by bvanderdrift** [comment]
I don´t think that requirement should need an endpoint that lists all tickets, but merely an endpoint that can get a ticket with a username. (Or another method to identify the user, have you thought about this?).

**Comment by Icety** [comment]
Fixed in #230
