### ISSUE TITLE
Mail for Seat reservation

### ISSUE THREAD

**Issue by bvanderdrift** [AreaFiftyLAN/lancie-api#224]
If you've reserved a seat yourself or your captain has placed/replaced you a user should be notified.

**Comment by Icety** [comment]
We decided that this should only be done when someone else changes or sets your seat.

**Comment by MatthijsKok** [comment]
We don't want this when a captain changes a seat. That would be highly abusable. Closing if no-one objects.

**Comment by skamoen** [comment]
Define "highly abusable"

**Comment by FrancisBehnen** [comment]
I agree. I was captain last year and changed the seats of the others at least 5 times per person.

**Comment by MatthijsKok** [comment]
ranging from unneeded to annoying

**Comment by skamoen** [comment]
Fixed if overidden by admin
