### ISSUE TITLE
Admin reserve seat override

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-api#233]
Once a seat is assigned, the admin should be able to override this action. The ticket should be changed to the ticket of the new seatholder.

**Comment by MatthijsKok** [comment]
This functionality already exists, since `currentUserServiceImpl.canReserveSeat` returns true when `principal` is `ADMIN`.

**Comment by skamoen** [comment]
Nope, Admins can reserve seats, but can't override already reserved seats. 

https://github.com/AreaFiftyLAN/lancie-api/blob/master/src/main/java/ch/wisv/areafiftylan/seats/service/SeatServiceImpl.java#L90
