### ISSUE TITLE
Application in dev does not boot after second load

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-api#234]
The `application.properties.sample` misses the line `spring.jpa.hibernate.ddl-auto=create`. If you do not specify this, you will get the error `ERROR: duplicate key value violates unique constraint "username"` for consecutive runs. However, as @skamoen pointed out: in production we do not want this value to be set. So this line should only be added for development.

**Comment by Icety** [comment]
Fixed in #247
