### ISSUE TITLE
ContainerElement 

### ISSUE THREAD

**Issue by svenpopping** [AreaFiftyLAN/lancie-api#25]
Container element is a element that contains the sections in on the webpage. So it keeps tracks of the size of the window. See old container element

- [x] Dark and normal mode
- [ ] Auto title element with long and short title

**Comment by TimvdLippe** [comment]
@svenpopping https://github.com/AreaFiftyLAN/lancie-section-element is the implementation of this issue, isn't it?

**Comment by skamoen** [comment]
Fixed somewhere in front-end.
