### ISSUE TITLE
User should be unable to create team without ticket

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-api#252]
Right now, a user is unable to be invited while he has no ticket. To be consistent, a user should also be unable to create a team while he has no ticket.

**Comment by bvanderdrift** [comment]
What is the motivation behind this? Why is consistency in this field useful?

**Comment by martijn9612** [comment]
A user cannot invite a user to a team if that user has no ticket. So  why would a user be able to create a team without a ticket? The user is not able to register for a tournament without a ticket and not able to reserve a seat. Why does he have to have a team when no actions can be perforned with the team?

**Comment by skamoen** [comment]
Policy change, Teams are now independent from tickets
