### ISSUE TITLE
Commission element

### ISSUE THREAD

**Issue by svenpopping** [AreaFiftyLAN/lancie-api#26]
- Uses API to load the data.
- Option on the admin panel to change the data

**Comment by svenpopping** [comment]
Data structure which is used in the frontend
```json
 {
    "function": "Chairman",
    "name": "1",
    "icon": "group"
  }
```

**Comment by TimvdLippe** [comment]
Not sure if this is still a big requirement, as it is currently handled on the frontend.

**Comment by skamoen** [comment]
This is still here because it's currently loaded from a static json file. This is supposed to go into /web endpoint eventually, just like the events
