### ISSUE TITLE
Edit texts on the homepage

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-api#280]
You need to be able to edit each title + subtext on the frontpage

**Comment by skamoen** [comment]
These texts should be scheduled, turning them in some sort of "Message of the day".

A single endpoint `/web/motd` would return for example the `title` and `subtitle` in Markdown. Then you can plan these messages years ahead, preventing out-of-date messages.

**Comment by martijnjanssen** [comment]
#268

**Comment by skamoen** [comment]
I'm not sure a full section CMS-like system is worth the effort, if you see how easy the last text change was without . Closing this.
