### ISSUE TITLE
Resolve warnings in Application startup

### ISSUE THREAD

**Issue by MatthijsKok** [AreaFiftyLAN/lancie-api#305]
- [ ] Found use of deprecated [org.hibernate.id.SequenceGenerator] sequence-based id generator; use org.hibernate.id.enhanced.SequenceStyleGenerator instead.  See Hibernate Domain Model Mapping Guide for details.

**Comment by skamoen** [comment]
This is the javax.persistence `@GeneratedValue` annotation. Not something for us to fix, this will probably be updated in a Hibernate update as part of a Spring update.

**Comment by Tejaswini525** [comment]
this issue solved??

**Comment by sravanthi555** [comment]
Hi
Did this issue got solved?
Even am getting the same warns.
How do I resolve it?

**Comment by skamoen** [comment]
Fixed in #490
