### ISSUE TITLE
The plugin id 'spring-boot' is deprecated. Please use 'org.springframework.boot' instead.

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-api#309]
Running the Application shows a deprecation warning in the console:

> The plugin id 'spring-boot' is deprecated. Please use 'org.springframework.boot' instead.

I think https://github.com/AreaFiftyLAN/lancie-api/blob/8dad7f48a1942bf944a6635bd360e92b880d92c1/build.gradle#L16 should be updated to `org.springframework.boot`

**Comment by skamoen** [comment]
We can also upgrade gradle itself while we're at it. Replace 2.11 with 3.2.1 probably does the trick
