### ISSUE TITLE
Log successful login after X tries

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-api#311]
Similar to a wrong `sudo` password, we should investigate if it's possible to delay the 40* response when a login is incorrect. This will reduce the brute-force capability.

**Comment by MatthijsKok** [comment]
I really like [this answer](http://security.stackexchange.com/a/94434) on this issue. Maybe accountbount throttling will be a better idea.

**Comment by skamoen** [comment]
Automatic throttling seems to be hard, as there are many scenario's where it's quite easy to go around the protection, or hinder legitimate users. Perhaps it's an idea to keep track (on a per user basis) if a login attempt takes a lot of tries. 

Something similar as this: http://www.baeldung.com/spring-security-block-brute-force-authentication-attempts but instead it sends us an email when a user successfully logs in after >50 tries?

**Comment by skamoen** [comment]
I think adding an `else` [https://github.com/AreaFiftyLAN/lancie-api/blob/master/src/main/java/ch/wisv/areafiftylan/security/authentication/AuthenticationServiceImpl.java#L56](here) is easier. However, this is super low prio so let's not worry about this now.

**Comment by MatthijsKok** [comment]
With #331 Merged, does this get any easier?

**Comment by skamoen** [comment]
Yes, we could implement a FailureHandler just like the SuccessHandler where we keep track of failed login. the SuccessHandler could then check the amount of unsuccessful logins in the past X minutes
