### ISSUE TITLE
Assign new ticket to user as Admin

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-api#358]
If we use the adminApprove() function on a PENDING order, it is changed to PAID. However, as Mollie will expire the Order after a while, it will push that status to the API. It will probably override the previous PAID order, with unknown consequences. 

Two possible fixes:
1. Only allow admin-approval on ASSIGNED orders
2. Check for PAID status in the Mollie webhook 

I think option 1 is the easiest.

**Comment by martijnjanssen** [comment]
I would check whether the order is already PAID, since this is what I would expect to happen. Only approve on ASSIGNED orders would be kinda odd, but why add an entire order? It shouldn't be an order at the start, since the tickets are not bought. You should just add tickets in my opinion.

**Comment by MatthijsKok** [comment]
I agree with Martijn. An admin should be able to create tickets for users, independent of orders.
