### ISSUE TITLE
Reserve entire Seatgroups without assigning tickets.

### ISSUE THREAD

**Issue by MatthijsKok** [AreaFiftyLAN/lancie-api#369]
Useful when a group wants an entire island.

**Comment by skamoen** [comment]
I'd make this more generic. The case where you want to reserve exactly a group seems rare and very single-use. 

Instead, I'd go for a way to reserve multiple seats in the API, and make lancie-admin functionality to select these seats and build the request.

**Comment by martijnjanssen** [comment]
We already have this [functionality](https://github.com/AreaFiftyLAN/lancie-api/blob/master/src/main/java/ch/wisv/areafiftylan/seats/controller/SeatRestController.java#L123-L136)

**Comment by MatthijsKok** [comment]
Fixed in #424
