### ISSUE TITLE
OPERATOR Role endpoint rules

### ISSUE THREAD

**Issue by MatthijsKok** [AreaFiftyLAN/lancie-api#387]
We would call this Role OPERATOR, this access level is between the level of USER and ADMIN. This would imply that any method requiring OPERATOR would also be accessible to ADMINs.
We should at the same time look into chaining Role levels, like View allows.

**Comment by martijnjanssen** [comment]
We already have a [COMMITTEE](https://github.com/AreaFiftyLAN/lancie-api/blob/master/src/main/java/ch/wisv/areafiftylan/users/model/Role.java#L23) role, we can use this role without any problem for this purpose.

**Comment by MatthijsKok** [comment]
At this time there is no chaining though, right?

**Comment by skamoen** [comment]
It may be a good idea to separate ADMIN, COMMITTEE and OPERATATOR roles more clearly. Not everyone from the committee needs access to everything, but more then someone from the crew. Let's design this properly, taking multiple usecases into account. 

Furthermore, there's this: http://docs.spring.io/spring-security/site/docs/4.0.0.RELEASE/apidocs/org/springframework/security/access/hierarchicalroles/RoleHierarchy.html

I know Sven Popping briefly looked at this for a project, but wasn't successful. This can be done manually using the currentUserServiceImpl, but I'd rather go for something more elegant.
