### ISSUE TITLE
Rework CurrentUserServiceImpl

### ISSUE THREAD

**Issue by MatthijsKok** [AreaFiftyLAN/lancie-api#428]
We can make a lot of improvements with the new RoleHierarchy.

Do we also want to pull any admin override logic out of that class, and use the SpEL instead?
Something like 
`@PreAuthorize("@currentUserServiceImpl.canReserveSeat(principal, #ticketId) OR hasRole('ADMIN')")`
is the current standard, and the built in `hasRole()` now uses the Hierarchy

**Comment by skamoen** [comment]
Is this fixed in #435 or did you have additional changes in mind?

**Comment by MatthijsKok** [comment]
We need to reasses wether the methods need admin privileges or lower
