### ISSUE TITLE
Upgrade to Java 9 

### ISSUE THREAD

**Issue by MatthijsKok** [AreaFiftyLAN/lancie-api#444]
Java 9 brings a lot of new features that we would love, however we will need to wait for some of our dependencies to be updated, namely:
- [x] Lombok, issue tracked [here](https://github.com/rzwitserloot/lombok/issues/985)
- [x] Spring Framework 5, [released!](https://spring.io/blog/2017/09/28/spring-framework-5-0-goes-ga)
- [x] Spring Boot 2.0, tracked [here](https://github.com/spring-projects/spring-boot/issues/7226) "Within well defined limitations [wiki]{https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9}

When we get Java 9 up and running, we can:
- [ ] Modularize our system
- [ ] Look into implementing HTTP2.0
- [ ] Use nice new Collection creation methods

**Comment by TimvdLippe** [comment]
I think Mockito is not 100% Java 9 compatible, but I need to check it

**Comment by skamoen** [comment]
Let's not worry about this until Spring Boot 2.0. That's planned for the end of November. Seeing as a lot of projects seem to have issues, there's no rush here

**Comment by Foorack** [comment]
Spring Boot 2.0 now builds with Java 9.

**Comment by skamoen** [comment]
The Gradle plugin for Spring Boot 2.0.0 contains several changes as well, see https://spring.io/blog/2017/04/05/spring-boot-s-new-gradle-plugin

**Comment by martijnjanssen** [comment]
Spring boot has now been updated since #490, that is no longer an issue for the java 9 upgrade.

**Comment by TimvdLippe** [comment]
Mockito 2 should now also build with Java 9 btw
