### ISSUE TITLE
Remove icon groups from committee member icons

### ISSUE THREAD

**Issue by elarb** [AreaFiftyLAN/lancie-api#447]
The icon groups aren't needed anymore since there is a fixed set of icons we are using for the committee memers. 

Related PR: https://github.com/AreaFiftyLAN/lancie-frontend/pull/517

**Comment by martijnjanssen** [comment]
Forunately, we didn't even implement that to allow more freedom specifying the icons. [As you can see here](https://github.com/AreaFiftyLAN/lancie-api/blob/master/src/main/java/ch/wisv/areafiftylan/web/committee/model/CommitteeMember.java#L21), the icon only consists of a string! No changes needed 🎉
