### ISSUE TITLE
Password can be changed to the same password

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-api#495]
https://github.com/AreaFiftyLAN/lancie-api/blob/baa642caee5da1e0655c55349621f15be1bd79d9/src/main/java/ch/wisv/areafiftylan/users/controller/CurrentUserRestController.java#L79-L96

**Comment by martijnjanssen** [comment]
Oh, I don't mean the reset functionality, I was talking about the password edit in my-area

**Comment by skamoen** [comment]
![image](https://user-images.githubusercontent.com/3198784/46256716-cd266800-c4ae-11e8-9e40-d6712bb7479b.png)
