### ISSUE TITLE
CORS errors on some endpoints

### ISSUE THREAD

**Issue by dsluijk** [AreaFiftyLAN/lancie-api#542]
We are getting CORS errors on some endpoints. This might be on all PUT requests, but this has to be verified. As the impact is unknown we should look into it soon.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.areafiftylan.nl/api/v1/tickets/tickettype/5186. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.areafiftylan.nl/api/v1/tickets/tickettype/5186. (Reason: CORS request did not succeed).
```

**Comment by skamoen** [comment]
You need to add allowed methods here: https://github.com/AreaFiftyLAN/lancie-api/blob/master/src/main/java/ch/wisv/areafiftylan/security/SecurityConfiguration.java#L126

It seems by default only GET, POST and OPTIONS are allowed

**Comment by dsluijk** [comment]
Solved
