### ISSUE TITLE
Order model

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-api#66]
We need a model for the Order object

- [x] Contains a single or multiple tickets
- [x] Is linked to a single User
- [x] A single User can have multiple Orders
- [x] A price, based on the contained Tickets
- [x] A status (paid, cancelled ect)

**Comment by TimvdLippe** [comment]
[Comment on old branch](https://github.com/AreaFiftyLAN/lancie-api/commit/d99095e0f0541b207269bc145627a60329910c5b#commitcomment-15080724)

**Comment by skamoen** [comment]
Fixed in #86
