### ISSUE TITLE
Licenses & such

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-api#83]
Figure out a suitable license model, and update the copyright message in every file to accomodate.

**Comment by skamoen** [comment]
I think [The GNU GPL V3](http://choosealicense.com/licenses/gpl-3.0/) license is the best option here. Distributing this commercially would cause a lot of headaches and possible conflicts. In the future, commercialization could be done with support and hosting options. 

GPL ensures any 3rd party improvements and changes are published. 

Thoughts?

**Comment by TimvdLippe** [comment]
Yes that seems the best option. If other parties are using the same software, the LANcie can benefit from their contributions too.
