### ISSUE TITLE
Investigate Lombok use

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-api#95]
To get rid of getters and setters in DTO's, we may consider using Lombok.

This guide uses it: https://jaxenter.com/rest-api-spring-java-8-112289.html

**Comment by martijn9612** [comment]
To use lombok, you need to check **Enable annotation processing** in  **Build, Execution, Deployment** > **Compiler** > **Annotation Processors**. Also add lombok to the "Annotation Processors" under "Processor FQ Name" and you are ready to go! You may also want to check out the lombok plugin for IntelliJ.

**Comment by skamoen** [comment]
Fixed in #104
